<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.List,java.util.Map,model.EnqueteModel,model.OpcaoRespostaModel,model.UsuarioModel" %>
<% List<EnqueteModel> enquetes=(List<EnqueteModel>)request.getAttribute("enquetes"); Map<Integer,List<OpcaoRespostaModel>> opcoes=(Map<Integer,List<OpcaoRespostaModel>>)request.getAttribute("opcoesPorEnquete"); UsuarioModel usuario=(UsuarioModel)session.getAttribute("usuarioLogado"); %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Enquetes</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-gray-100 p-8"><div class="max-w-6xl mx-auto"><div class="flex justify-between items-center mb-6"><div><h1 class="text-3xl font-bold">Enquetes</h1><p class="text-gray-600">Escolha uma enquete disponível.</p></div><div><% if(usuario!=null&&usuario.getNivelAcesso()!=null&&usuario.getNivelAcesso().getIdNivelAcesso()==2){ %><a href="enquete?acao=novo" class="bg-indigo-600 text-white px-4 py-2 rounded mr-2">Nova enquete</a><a href="categoria?acao=listar" class="bg-slate-700 text-white px-4 py-2 rounded">Categorias</a><% } %></div></div>
<% if(request.getParameter("erro")!=null){ %><div class="bg-red-50 text-red-700 border border-red-200 rounded p-3 mb-4">Erro: <%=request.getParameter("erro")%></div><% } %>
<% if(request.getParameter("sucesso")!=null){ %><div class="bg-emerald-50 text-emerald-700 border border-emerald-200 rounded p-3 mb-4">Voto registrado com sucesso.</div><% } %>
<div class="grid md:grid-cols-2 gap-6"><% if(enquetes!=null) for(EnqueteModel e:enquetes){ List<OpcaoRespostaModel> lista=opcoes.get(e.getIdEnquete()); %><div class="bg-white rounded-xl shadow p-6"><div class="flex justify-between"><h2 class="text-xl font-bold"><%=e.getTitulo()%></h2><span class="text-xs px-2 py-1 rounded bg-gray-100"><%=e.getStatus()%></span></div><p class="text-gray-600 my-3"><%=e.getDescricao()%></p><p class="text-sm text-gray-500 mb-3">Categoria: <%=e.getCategoria()==null?"-":e.getCategoria().getNomeCategoria()%></p>
<form method="post" action="voto"><input type="hidden" name="idEnquete" value="<%=e.getIdEnquete()%>"><div class="space-y-2"><% if(lista!=null) for(OpcaoRespostaModel op:lista){ %><label class="block border rounded p-3"><input type="<%="MULTIPLA".equals(e.getTipoVotacao())?"checkbox":"radio"%>" name="idOpcao" value="<%=op.getIdOpcao()%>" class="mr-2"><%=op.getDescricaoOpcao()%></label><% } %></div><button class="mt-4 bg-indigo-600 text-white px-4 py-2 rounded" type="submit" <%=!"EM_CURSO".equals(e.getStatus())?"disabled":""%>>Votar</button></form>
<% if(usuario!=null&&usuario.getNivelAcesso()!=null&&usuario.getNivelAcesso().getIdNivelAcesso()==2){ %><div class="mt-4 text-sm"><a class="text-indigo-600 mr-3" href="enquete?acao=editar&id=<%=e.getIdEnquete()%>">Editar</a><a class="text-red-600" href="enquete?acao=excluir&id=<%=e.getIdEnquete()%>" onclick="return confirm('Excluir enquete?')">Excluir</a></div><% } %>
</div><% } %></div><div class="mt-6"><a class="text-indigo-600" href="<%=usuario!=null&&usuario.getNivelAcesso()!=null&&usuario.getNivelAcesso().getIdNivelAcesso()==2?"usuario_adm.jsp":"usuario_comum.jsp"%>">← Voltar</a></div></div></body></html>