<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="model.EnqueteModel,model.CategoriaModel,java.util.List" %>
<% EnqueteModel enquete=(EnqueteModel)request.getAttribute("enquete"); boolean editar=enquete!=null; List<CategoriaModel> categorias=(List<CategoriaModel>)request.getAttribute("categorias"); %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Enquete</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-gray-100 p-8"><div class="max-w-2xl mx-auto bg-white rounded-xl shadow p-6"><h1 class="text-2xl font-bold mb-6"><%=editar?"Editar":"Criar"%> Enquete</h1>
<% if(request.getAttribute("erro")!=null){ %><div class="bg-red-50 text-red-700 border border-red-200 rounded p-3 mb-4"><%=request.getAttribute("erro")%></div><% } %>
<form method="post" action="enquete" class="space-y-4"><input type="hidden" name="acao" value="<%=editar?"atualizar":"inserir"%>"><% if(editar){ %><input type="hidden" name="idEnquete" value="<%=enquete.getIdEnquete()%>"><% } %>
<input class="w-full border rounded p-2" name="titulo" required placeholder="Título" value="<%=editar?enquete.getTitulo():""%>">
<textarea class="w-full border rounded p-2" name="descricao" required placeholder="Descrição"><%=editar?enquete.getDescricao():""%></textarea>
<div><label>Tipo</label><select class="w-full border rounded p-2" name="tipoVotacao"><option value="UNICA" <%=editar&&"UNICA".equals(enquete.getTipoVotacao())?"selected":""%>>Escolha única</option><option value="MULTIPLA" <%=editar&&"MULTIPLA".equals(enquete.getTipoVotacao())?"selected":""%>>Múltipla escolha</option></select></div>
<div class="grid grid-cols-2 gap-3"><input class="border rounded p-2" type="number" min="0" name="limiteVotosIp" value="<%=editar?enquete.getLimiteVotosIp():0%>" placeholder="Limite por IP (0 = sem limite)"><input class="border rounded p-2" type="number" min="0" name="limiteQuantidadeVotos" value="<%=editar?enquete.getLimiteQuantidadeVotos():0%>" placeholder="Limite total (0 = sem limite)"></div>
<select class="w-full border rounded p-2" name="idCategoria" required><option value="">Selecione a categoria</option><% if(categorias!=null) for(CategoriaModel c:categorias){ %><option value="<%=c.getIdCategoria()%>" <%=editar&&enquete.getCategoria()!=null&&enquete.getCategoria().getIdCategoria()==c.getIdCategoria()?"selected":""%>><%=c.getNomeCategoria()%></option><% } %></select>
<input class="w-full border rounded p-2" type="datetime-local" name="dataExpiracao" required value="<%=editar&&enquete.getDataExpiracao()!=null?enquete.getDataExpiracao().toString():""%>">
<div><label>Opções de resposta (mínimo 2)</label><input class="w-full border rounded p-2" name="opcao" required placeholder="Opção 1"><input class="w-full border rounded p-2 mt-2" name="opcao" required placeholder="Opção 2"></div>
<button class="bg-indigo-600 text-white px-4 py-2 rounded">Salvar enquete</button> <a class="text-indigo-600 ml-3" href="enquete?acao=listar">Cancelar</a></form></div></body></html>