<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="model.EnqueteModel,model.CategoriaModel,model.OpcaoRespostaModel,java.util.List,java.time.format.DateTimeFormatter" %>
<% EnqueteModel enquete=(EnqueteModel)request.getAttribute("enquete"); boolean editar=enquete!=null; List<CategoriaModel> categorias=(List<CategoriaModel>)request.getAttribute("categorias"); List<OpcaoRespostaModel> existentes=(List<OpcaoRespostaModel>)request.getAttribute("opcoesExistentes"); DateTimeFormatter fmtBr=DateTimeFormatter.ofPattern("dd/MM/yyyy"); %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><%=editar?"Editar":"Criar"%> Enquete</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-gray-100 p-6"><div class="max-w-2xl mx-auto bg-white rounded-xl shadow p-6"><h1 class="text-2xl font-bold mb-6"><%=editar?"Editar":"Criar"%> Enquete</h1>
<% if(request.getAttribute("erro")!=null){ %><div class="bg-red-50 text-red-700 border border-red-200 rounded p-3 mb-4"><%=request.getAttribute("erro")%></div><% } %>
<form method="post" action="<%=request.getContextPath()%>/enquete" class="space-y-4"><input type="hidden" name="acao" value="<%=editar?"atualizar":"inserir"%>"><% if(editar){ %><input type="hidden" name="idEnquete" value="<%=enquete.getIdEnquete()%>"><% } %>
<div><label class="text-sm font-medium">Título</label><input class="w-full border rounded p-2" name="titulo" required maxlength="255" value="<%=editar?enquete.getTitulo():""%>"></div>
<div><label class="text-sm font-medium">Descrição</label><textarea class="w-full border rounded p-2" name="descricao" required maxlength="1000"><%=editar?enquete.getDescricao():""%></textarea></div>
<div><label class="text-sm font-medium">Tipo de votação</label><select class="w-full border rounded p-2" name="tipoVotacao"><option value="UNICA" <%=editar&&"UNICA".equals(enquete.getTipoVotacao())?"selected":""%>>Escolha única</option><option value="MULTIPLA" <%=editar&&"MULTIPLA".equals(enquete.getTipoVotacao())?"selected":""%>>Múltipla escolha</option></select></div>
<div class="grid sm:grid-cols-2 gap-3"><div><label class="text-sm font-medium">Máx. usuários por IP</label><input class="w-full border rounded p-2" type="number" min="0" name="limiteVotosIp" value="<%=editar?enquete.getLimiteVotosIp():0%>"></div><div><label class="text-sm font-medium">Limite total de votos</label><input class="w-full border rounded p-2" type="number" min="0" name="limiteQuantidadeVotos" value="<%=editar?enquete.getLimiteQuantidadeVotos():0%>"></div></div>
<div><label class="text-sm font-medium">Categoria</label><select class="w-full border rounded p-2" name="idCategoria" required><option value="">Selecione</option><% if(categorias!=null) for(CategoriaModel c:categorias){ %><option value="<%=c.getIdCategoria()%>" <%=editar&&enquete.getCategoria()!=null&&enquete.getCategoria().getIdCategoria()==c.getIdCategoria()?"selected":""%>><%=c.getNomeCategoria()%></option><% } %></select></div>
<div><label class="text-sm font-medium">Expiração (dd/mm/aaaa)</label><input class="w-full border rounded p-2" type="text" id="data-expiracao" name="dataExpiracao" required inputmode="numeric" maxlength="10" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" autocomplete="off" placeholder="dd/mm/aaaa" title="Informe a data no formato dd/mm/aaaa" value="<%=editar&&enquete.getDataExpiracao()!=null?enquete.getDataExpiracao().format(fmtBr):""%>"></div>
<% if(!editar){ %><div><label class="text-sm font-medium">Opções de resposta (mínimo 2)</label><input class="w-full border rounded p-2" name="opcao" required maxlength="255" placeholder="Opção 1"><input class="w-full border rounded p-2 mt-2" name="opcao" required maxlength="255" placeholder="Opção 2"><input class="w-full border rounded p-2 mt-2" name="opcao" maxlength="255" placeholder="Opção 3 (opcional)"></div><% } else { %><div class="bg-gray-50 rounded p-4"><p class="text-sm font-medium mb-2">Opções atuais</p><ul class="list-disc ml-5 text-sm text-gray-600"><% if(existentes!=null) for(OpcaoRespostaModel o:existentes){ %><li><%=o.getDescricaoOpcao()%></li><% } %></ul><a class="inline-block mt-3 text-indigo-600 text-sm" href="<%=request.getContextPath()%>/opcao?acao=listar&idEnquete=<%=enquete.getIdEnquete()%>">Gerenciar opções separadamente →</a></div><% } %>
<button class="bg-indigo-600 text-white px-4 py-2 rounded">Salvar enquete</button><a class="text-indigo-600 ml-3" href="<%=request.getContextPath()%>/dashboard">Cancelar</a></form></div><script>
const dataExp=document.getElementById('data-expiracao');
if(dataExp){
  dataExp.addEventListener('input',()=>{const d=dataExp.value.replace(/\D/g,'').slice(0,8);dataExp.value=d.length<=2?d:d.length<=4?d.slice(0,2)+'/'+d.slice(2):d.slice(0,2)+'/'+d.slice(2,4)+'/'+d.slice(4);});
}
</script></body></html>
