<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.*,java.time.format.DateTimeFormatter,model.*,dao.*" %>
<%!
private String esc(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
%>
<%
request.setCharacterEncoding("UTF-8"); response.setCharacterEncoding("UTF-8");
UsuarioModel logado=(UsuarioModel)session.getAttribute("usuarioLogado");
if(logado==null||logado.getNivelAcesso()==null||logado.getNivelAcesso().getIdNivelAcesso()!=2){response.sendRedirect(request.getContextPath()+"/index.jsp");return;}
UsuarioDAO usuarioDAO=new UsuarioDAO(); NivelAcessoDAO nivelDAO=new NivelAcessoDAO();
List<UsuarioModel> usuarios=usuarioDAO.listarTodos(); List<NivelAcessoModel> niveis=nivelDAO.listarTodos();
UsuarioModel editando=(UsuarioModel)request.getAttribute("usuario");
if(editando==null && request.getParameter("id")!=null){try{editando=usuarioDAO.buscarPorId(Integer.parseInt(request.getParameter("id")));}catch(Exception ignored){}}
DateTimeFormatter dataHora=DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
%>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Usuários</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="bg-slate-100 p-5"><div class="max-w-7xl mx-auto"><div class="flex flex-wrap justify-between items-center gap-3 mb-5"><div><h1 class="text-2xl font-bold">Gerenciamento de usuários</h1><p class="text-sm text-slate-500">Dados reais da tabela <code>usuario</code>.</p></div><a class="border px-4 py-2 rounded-lg" href="<%=request.getContextPath()%>/dashboard">← Dashboard</a></div>
<% if(editando!=null){ %><form method="post" action="<%=request.getContextPath()%>/usuario" class="bg-white border rounded-xl p-5 mb-6 grid md:grid-cols-2 gap-4"><input type="hidden" name="acao" value="atualizar"><input type="hidden" name="idUsuario" value="<%=editando.getIdUsuario()%>"><div><label class="text-sm font-medium">Nome</label><input class="w-full border rounded-lg p-2.5" name="nome" required maxlength="100" value="<%=esc(editando.getNome())%>"></div><div><label class="text-sm font-medium">E-mail</label><input class="w-full border rounded-lg p-2.5" type="email" name="email" required maxlength="150" value="<%=esc(editando.getEmail())%>"></div><div><label class="text-sm font-medium">Nova senha <span class="text-slate-400">(deixe vazio para manter)</span></label><input class="w-full border rounded-lg p-2.5" type="password" name="senha"></div><div><label class="text-sm font-medium">Perfil</label><select class="w-full border rounded-lg p-2.5" name="idNivel"><% for(NivelAcessoModel n:niveis){ %><option value="<%=n.getIdNivelAcesso()%>" <%=editando.getNivelAcesso()!=null&&editando.getNivelAcesso().getIdNivelAcesso()==n.getIdNivelAcesso()?"selected":""%>><%=esc(n.getTipo())%></option><% } %></select></div><div><label class="text-sm font-medium">Status</label><select class="w-full border rounded-lg p-2.5" name="status"><option value="1" <%=editando.getStatus()==1?"selected":""%>>Ativo</option><option value="0" <%=editando.getStatus()==0?"selected":""%>>Inativo</option></select></div><div class="flex items-end gap-3"><button class="bg-indigo-600 text-white px-4 py-2 rounded-lg">Salvar alterações</button><a class="border px-4 py-2 rounded-lg" href="<%=request.getContextPath()%>/usuario?acao=listar">Cancelar</a></div></form><% } %>
<div class="bg-white border rounded-xl overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="text-left p-3">ID</th><th class="text-left p-3">Nome</th><th class="text-left p-3">E-mail</th><th class="text-left p-3">Cadastro</th><th class="text-left p-3">Perfil</th><th class="text-left p-3">Status</th><th class="text-left p-3">Ações</th></tr></thead><tbody><% for(UsuarioModel u:usuarios){ %><tr class="border-t"><td class="p-3"><%=u.getIdUsuario()%></td><td class="p-3 font-medium"><%=esc(u.getNome())%></td><td class="p-3"><%=esc(u.getEmail())%></td><td class="p-3 whitespace-nowrap"><%=u.getDataCadastro()==null?"-":u.getDataCadastro().format(dataHora)%></td><td class="p-3"><%=esc(u.getNivelAcesso()==null?"-":u.getNivelAcesso().getTipo())%></td><td class="p-3"><%=u.getStatus()==1?"Ativo":"Inativo"%></td><td class="p-3 whitespace-nowrap"><a class="text-indigo-700 mr-3" href="<%=request.getContextPath()%>/usuario?acao=editar&id=<%=u.getIdUsuario()%>">Editar</a><% if(u.getIdUsuario()!=logado.getIdUsuario()){ %><a class="text-red-600" href="<%=request.getContextPath()%>/usuario?acao=excluir&id=<%=u.getIdUsuario()%>" onclick="return confirm('Excluir este usuário? A exclusão pode ser impedida se houver votos ou enquetes vinculados.')">Excluir</a><% } else { %><span class="text-slate-400">Usuário atual</span><% } %></td></tr><% } %></tbody></table></div></div></body></html>
