-- MySQL Script generated by MySQL Workbench
-- Thu Jul 23 15:01:30 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`nivel_acesso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nivel_acesso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nivel_acesso` (
  `idnivel_acesso` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `permissões` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnivel_acesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `data_cadastro` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `nivel_acesso_idnivel_acesso` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_nivel_acesso1_idx` (`nivel_acesso_idnivel_acesso` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_nivel_acesso1`
    FOREIGN KEY (`nivel_acesso_idnivel_acesso`)
    REFERENCES `mydb`.`nivel_acesso` (`idnivel_acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`enquete` ;

CREATE TABLE IF NOT EXISTS `mydb`.`enquete` (
  `idenquete` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `tipo_votacao` VARCHAR(45) NOT NULL,
  `limite_votos_ip` INT NOT NULL,
  `limite_quantidade_votos` INT NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `data_expiracao` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idenquete`),
  INDEX `fk_enquete_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_enquete_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_enquete_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enquete_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`opcao_resposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`opcao_resposta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`opcao_resposta` (
  `idopcao` INT NOT NULL,
  `descrição_opcao` VARCHAR(45) NOT NULL,
  `enquete_idenquete` INT NOT NULL,
  PRIMARY KEY (`idopcao`),
  INDEX `fk_opcao_resposta_enquete1_idx` (`enquete_idenquete` ASC) VISIBLE,
  CONSTRAINT `fk_opcao_resposta_enquete1`
    FOREIGN KEY (`enquete_idenquete`)
    REFERENCES `mydb`.`enquete` (`idenquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`voto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`voto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`voto` (
  `data_hora_voto` DATETIME NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `enquete_idenquete` INT NOT NULL,
  `opcao_resposta_idopcao` INT NOT NULL,
  PRIMARY KEY (`enquete_idenquete`, `usuario_idusuario`),
  INDEX `fk_voto_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_voto_enquete1_idx` (`enquete_idenquete` ASC) VISIBLE,
  INDEX `fk_voto_opcao_resposta1_idx` (`opcao_resposta_idopcao` ASC) VISIBLE,
  CONSTRAINT `fk_voto_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voto_enquete1`
    FOREIGN KEY (`enquete_idenquete`)
    REFERENCES `mydb`.`enquete` (`idenquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voto_opcao_resposta1`
    FOREIGN KEY (`opcao_resposta_idopcao`)
    REFERENCES `mydb`.`opcao_resposta` (`idopcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
